# Generated by Django 5.0.2 on 2025-05-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('invoice_type', models.CharField(choices=[('rent', 'إيجار'), ('service', 'خدمة'), ('maintenance', 'صيانة'), ('penalty', 'غرامة'), ('other', 'أخرى')], default='rent', max_length=20, verbose_name='نوع الفاتورة')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ضريبة القيمة المضافة')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ الإجمالي')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم السداد؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=50, unique=True, verbose_name='رقم السداد')),
                ('payment_date', models.DateField(verbose_name='تاريخ السداد')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('bank_transfer', 'حوالة بنكية'), ('cheque', 'شيك'), ('credit_card', 'بطاقة ائتمان'), ('other', 'أخرى')], default='bank_transfer', max_length=20, verbose_name='طريقة السداد')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='رقم المرجع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('receipt_attachment', models.FileField(blank=True, null=True, upload_to='payments/receipts/', verbose_name='إيصال السداد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'سداد',
                'verbose_name_plural': 'السدادات',
                'ordering': ['-payment_date'],
            },
        ),
    ]
