# Generated by Django 5.0.2 on 2025-05-06 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الرخصة')),
                ('agency_name', models.CharField(max_length=100, verbose_name='اسم الوكالة')),
                ('phone', models.CharField(max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('specialization', models.CharField(choices=[('commercial', 'عقارات تجارية'), ('residential', 'عقارات سكنية'), ('industrial', 'عقارات صناعية'), ('all', 'كل أنواع العقارات')], default='all', max_length=50, verbose_name='التخصص')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_agent', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'وسيط عقاري',
                'verbose_name_plural': 'الوسطاء العقاريون',
            },
        ),
    ]
