# Generated by Django 5.0.2 on 2025-05-06 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='رقم العقد')),
                ('contract_type', models.CharField(choices=[('commercial_lease', 'إيجار تجاري'), ('residential_lease', 'إيجار سكني'), ('investment', 'استثمار'), ('sale', 'بيع'), ('company_shares', 'بيع حصص شركات')], default='commercial_lease', max_length=20, verbose_name='نوع العقد')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الإيجار الشهري')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المبلغ الإجمالي')),
                ('secrity_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الضمان المالي')),
                ('paymnet_terms', models.TextField(blank=True, verbose_name='شروط السداد')),
                ('special_terms', models.TextField(blank=True, verbose_name='شروط خاصة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.realestateagent', verbose_name='الوسيط العقاري')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='tenants.company', verbose_name='المستأجر')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='properties.unit', verbose_name='الوحدة العقارية')),
            ],
            options={
                'verbose_name': 'عقد',
                'verbose_name_plural': 'العقود',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract_copy', 'نسخه من العقد'), ('id_copy', 'نسخه من الهوية/السجل التجاري'), ('insurance', 'وثيقة التأمين'), ('other', 'مستند أخرى')], max_length=50, verbose_name='نوع المستند')),
                ('file', models.FileField(upload_to='contracts/documents/', verbose_name='الملف')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'مستند العقد',
                'verbose_name_plural': 'مستندات العقود',
            },
        ),
    ]
