# Generated by Django 5.0.2 on 2025-05-06 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخدمة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الخدمة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
            ],
            options={
                'verbose_name': 'نوع الخدمة',
                'verbose_name_plural': 'أنواع الخدمات',
            },
        ),
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=200, verbose_name='اسم مقدم الخدمة')),
                ('contract_number', models.CharField(max_length=50, verbose_name='رقم العقد')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='التكلفة الشهرية')),
                ('terms', models.TextField(blank=True, verbose_name='شروط العقد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_contracts', to='properties.building', verbose_name='المبنى')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='services.servicetype', verbose_name='نوع الخدمة')),
            ],
            options={
                'verbose_name': 'عقد خدمة',
                'verbose_name_plural': 'عقود الخدمات',
            },
        ),
        migrations.CreateModel(
            name='ServiceInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم السداد؟')),
                ('service_contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='services.servicecontract', verbose_name='عقد الخدمة')),
            ],
            options={
                'verbose_name': 'فاتورة خدمة',
                'verbose_name_plural': 'فواتير الخدمات',
            },
        ),
    ]
