# Generated by Django 5.0.2 on 2025-05-06 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المبنى')),
                ('building_type', models.CharField(choices=[('commercial', 'تجاري'), ('residential', 'سكني'), ('mixed', 'مختلط')], default='commercial', max_length=20, verbose_name='نوع المبنى')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('city', models.CharField(max_length=50, verbose_name='المدينة')),
                ('total_floors', models.PositiveIntegerField(verbose_name='إجمالي الطوابق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مبنى',
                'verbose_name_plural': 'المباني',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.PositiveIntegerField(verbose_name='رقم الطابق')),
                ('total_units', models.PositiveIntegerField(verbose_name='إجمالي الوحدات')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='properties.building', verbose_name='المبنى')),
            ],
            options={
                'verbose_name': 'طابق',
                'verbose_name_plural': 'الطوابق',
                'unique_together': {('building', 'floor_number')},
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=20, verbose_name='رقم الوحدة')),
                ('unit_type', models.CharField(choices=[('apartment', 'شقة'), ('office', 'مكتب'), ('store', 'محل تجاري'), ('warehouse', 'مستودع')], default='office', max_length=20, verbose_name='نوع الوحدة')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المساحة(متر مربع)')),
                ('status', models.CharField(choices=[('vacant', 'شاغر'), ('occupied', 'مشغول'), ('under_construction', 'تحت الصيانة')], default='vacant', max_length=20, verbose_name='الحالة')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.floor', verbose_name='الطابق')),
            ],
            options={
                'verbose_name': 'وحدة',
                'verbose_name_plural': 'الوحدات',
                'unique_together': {('floor', 'unit_number')},
            },
        ),
    ]
