# Generated by Django 5.0.2 on 2025-05-06 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التقرير')),
                ('report_type', models.CharField(choices=[('financial', 'مالي'), ('occupancy', 'نسبة الإشغال'), ('rent_collection', 'تحصيل الإيجار'), ('expenses', 'المصروفات'), ('custom', 'تقرير مخصص')], max_length=50, verbose_name='نوع التقرير')),
                ('template_file', models.FileField(blank=True, null=True, upload_to='reports/templates/', verbose_name='ملف القالب')),
                ('sql_query', models.TextField(blank=True, help_text='استخدم {building.id} و {start_date} و {end_date} كمتغيرات', verbose_name='استعلام SQL')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
            ],
            options={
                'verbose_name': 'قالب تقرير',
                'verbose_name_plural': 'قوالب التقارير',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('contract_expiry', 'انتهاء العقد'), ('payment_due', 'استحقاق دفعة'), ('document_expiry', 'انتهاء صلاحية مستند'), ('custom', 'إشعار مخصص')], max_length=50, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('is_sent', models.BooleanField(default=False, verbose_name='تم الإرسال؟')),
                ('sent_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='وقت الإرسال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='contracts.contract', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التقرير')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('report_file', models.FileField(upload_to='reports/generated/', verbose_name='ملف التقرير')),
                ('perameters', models.TextField(blank=True, default=dict, verbose_name='معلمات التقرير')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='properties.building', verbose_name='المبنى')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.reporttemplate', verbose_name='قالب التقرير')),
            ],
            options={
                'verbose_name': 'تقرير تم إنشاؤه',
                'verbose_name_plural': 'التقارير التي تم إنشاؤها',
                'ordering': ['-generated_at'],
            },
        ),
    ]
