# Generated by Django 5.0.2 on 2025-05-06 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القالب')),
                ('document_type', models.CharField(choices=[('official_letter', 'رسالة رسمية'), ('legal_notice', 'إنذار قانوني'), ('contract', 'عقد'), ('certificate', 'شهادة'), ('eviction_notice', 'إشعار إخلاء'), ('rent_increase', 'إشعار زيادة إيجار')], max_length=50, verbose_name='نوع المستند')),
                ('template_file', models.FileField(upload_to='documents/templates/', verbose_name='ملف القالب')),
                ('variables', models.TextField(help_text='قائمة بالمتغيرات التي يمكن استخدامها في القالب، مفصولة بفاصلة', verbose_name='المتغيرات المتاحة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
            ],
            options={
                'verbose_name': 'قالب مستند',
                'verbose_name_plural': 'قوالب المستندات',
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=50, unique=True, verbose_name='رقم المستند')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('document_file', models.FileField(upload_to='documents/generated/', verbose_name='ملف المستند')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='tenants.company', verbose_name='الشركة')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to='contracts.contract', verbose_name='العقد')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documenttemplate', verbose_name='القالب المستخدم')),
            ],
            options={
                'verbose_name': 'مستند تم إنشاؤه',
                'verbose_name_plural': 'المستندات التي تم إنشاؤها',
                'ordering': ['-issue_date'],
            },
        ),
    ]
